version: "2"

services:
  zk:
    image: bobrik/zookeeper
    restart: always        
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
    ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"
    networks:
     - mesosphere

  master:
    image: mesosphere/mesos-master:0.28.0-2.0.16.ubuntu1404
    restart: always        
    environment:
      MESOS_ZK: zk://zk:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: mesosphere
      MESOS_HOSTNAME: master
      MESOS_PORT: 5050
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
    ports:
     - "5050:5050"
    networks:
     - mesosphere

  slave-one:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    privileged: true
    restart: always        
    environment:
      MESOS_MASTER: zk://zk:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_HOSTNAME: 192.168.64.2
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[10000-10100]
    ports:
     - "5051:5051"
    volumes:
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - mesosphere

  slave-two:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    privileged: true
    restart: always        
    environment:
      MESOS_MASTER: zk://zk:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_HOSTNAME: 192.168.64.2
      MESOS_PORT: 5052
      MESOS_RESOURCES: ports(*):[10000-10100]
    ports:
     - "5052:5052"
    volumes:
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - mesosphere

  marathon:
    image: mesosphere/marathon:v1.0.0-RC1
    command: --master zk://zk:2181/mesos --zk zk://zk:2181/marathon
    restart: always
    ports:
     - "8080:8080"
    networks:
     - mesosphere

  chronos:
    image: mesosphere/chronos:chronos-2.5.0-0.1.20160223054243.ubuntu1404-mesos-0.27.1-2.0.226.ubuntu1404
    command: /usr/bin/chronos run_jar --http_port 8888 --master zk://zk:2181/mesos --zk_hosts zk://zk:2181/mesos
    restart: always
    ports:
     - "8888:8888"
    networks:
     - mesosphere
  
networks:
  mesosphere:
    driver: bridge